option(UBAANEXT_ENABLE_CPP26_EXPERIMENTS "Enable experimental C++26 features" OFF)
option(UBAANEXT_BUILD_TESTS "Build UBAA Next test targets" ON)
option(UBAANEXT_BUILD_CLI "Build the host CLI executable" ON)
option(UBAANEXT_BUILD_DESKTOP "Build the Slint desktop GUI executable" OFF)
option(UBAANEXT_BUILD_APP_RUNTIME "Build the shared host app runtime target" ON)
option(UBAANEXT_BUILD_BINDINGS "Build native API binding targets for embedding clients" OFF)
option(UBAANEXT_BUILD_LIVE_SMOKE "Build live smoke test targets; never enable in default offline validation" OFF)
option(UBAANEXT_FETCH_DEPS "Download missing third-party dependencies with FetchContent" OFF)
option(UBAANEXT_REQUIRE_OPTIONAL_DEPS "Fail configuration when an explicitly requested optional dependency is missing" OFF)
option(UBAANEXT_ENABLE_LINUX_LIBSECRET "Build the Linux Secret Service secure store adapter" OFF)
option(UBAANEXT_ENABLE_WINFSP "Enable Windows WinFsp mount frontend when the SDK/runtime is available" OFF)
option(UBAANEXT_ENABLE_CLOUD_FILES "Enable Windows Cloud Files sync-root frontend" OFF)
option(UBAANEXT_ENABLE_FUSE "Enable Linux FUSE mount frontend when libfuse is available" OFF)

if(NOT DEFINED UBAANEXT_ENABLE_MOCKS)
    if(CMAKE_BUILD_TYPE STREQUAL "Release")
        set(UBAANEXT_ENABLE_MOCKS OFF CACHE BOOL "Build and expose mock implementations")
    else()
        set(UBAANEXT_ENABLE_MOCKS ON CACHE BOOL "Build and expose mock implementations")
    endif()
endif()
